//page names
const navPages = [
    "Bottom Navigations",
    "Buttons",
    "Calendars",
    "Cards",
    "Chips",
    "Dropdowns",
    "Filter Layouts",
    "Forms",
    "Form Fields",
    "Links",
    "Modals",
    "Notifications",
    "Paginations",
    "Progress Indicators",
    "Searchs",
    "Selectors",
    "Snackbars",
    "Step Progress",
    "Tables",
    "Tabs",
    "Toasts",
    "Tooltips",
];